name: build

on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
  pull_request:
    paths:
      - '**/*.go'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.23'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
